x-http-proxy: &http-proxy ${HTTP_PROXY}
x-https-proxy: &https-proxy ${HTTPS_PROXY}
x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae07,uclvlddpragae08,api,web,cache,baserow

x-proxy-common: &proxy-common
  HTTP_PROXY: *http-proxy
  http_proxy: *http-proxy
  HTTPS_PROXY: *https-proxy
  https_proxy: *https-proxy
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

x-build-args-common: &build-args-common
  <<: *proxy-common
  HYLODE_UID: ${HYLODE_UID}

services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${API_PORT}:8000
    networks:
      - hyui

  web:
    build:
      dockerfile: docker/web/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - baserow
      - api
      - cache
    healthcheck:
      test: ["CMD", "./refresh_cache.sh"]
      interval: 5m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - hyui

  cache:
    build:
      dockerfile: docker/cache/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - "${CACHE_PORT}:8000"
    command: "-p default_keep=300"
    depends_on:
      - api
    networks:
      - hyui

  baserow:
    image: baserow/baserow:1.13.1
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${BASEROW_PORT}:80
    networks:
      - hyui
    volumes:
      - baserow-data:/baserow/data

  prometheus:
    image: prom/prometheus:latest
    environment:
      <<: *proxy-common
    env_file: .env
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - hyui

  grafana:
    build:
      dockerfile: docker/grafana/Dockerfile
      args:
        <<: *build-args-common
    env_file:
      - ./docker/grafana/config.monitoring
    environment:
      <<: *proxy-common
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/hyui_api.json"
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - hyui

networks:
  hyui:

volumes:
  baserow-data:
