x-http-proxy: &http-proxy ${HTTP_PROXY}
x-https-proxy: &https-proxy ${HTTPS_PROXY}
x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae07,uclvlddpragae08,api,web,baserow

x-proxy-common: &proxy-common
  HTTP_PROXY: *http-proxy
  http_proxy: *http-proxy
  HTTPS_PROXY: *https-proxy
  https_proxy: *https-proxy
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

x-build-args-common: &build-args-common
  <<: *proxy-common
  HYLODE_UID: ${HYLODE_UID}

services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${API_PORT}:8000
    networks:
      - hyui

  web:
    build:
      dockerfile: docker/web/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - api
    networks:
      - hyui

  cache:
    build:
      dockerfile: docker/cache/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - "${CACHE_PORT}:6081"
    command: "-p default_keep=300"
    depends_on:
      - api
      - web
    networks:
      - hyui

  baserow:
    image: baserow/baserow:1.13.1
    environment:
      <<: *proxy-common
    env_file: .env
    ports:
      - ${BASEROW_PORT}:80
    networks:
      - hyui
    volumes:
      - baserow-data:/baserow/data

networks:
  hyui:

volumes:
  baserow-data:
