
version: '3.8'

services:

  # API docker image / reads and wrangles data
  # returns data via fastapi to dash app
  api:
    build:
      context: ./src
      dockerfile: Dockerfile.api
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    # NOTE: the --reload flag means that edits are automtically redeployed
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/api:/usr/src/api
      - ./src/config:/usr/src/config
      - ./src/utils:/usr/src/utils
      - ./src/mock:/usr/src/mock
    ports:
      - "8094:8000"
    expose:
      - "8000"
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY=apps
      - no_proxy=apps
      - SERVICES=DOCKER
    env_file:
      - .env
      - .secrets

  # Dash (Plotly) docker image / web app that visualises results
  # reads data via requests from api app
  apps:
    build:
      context: ./src
      dockerfile: Dockerfile.apps
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    # TODO: this entry point command will run the app in debug mode
    #       should convert to uvicorn or similar server
    # TODO: convert to single landing page for all apps
    command: python apps/consults/index.py
    volumes:
      - ./src/apps:/usr/src/dash
      - ./src/config:/usr/src/config
      - ./src/utils:/usr/src/utils
      - ./src/mock:/usr/src/mock
      - ./src/api:/usr/src/api
    ports:
      - "8095:8095"
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY=api
      - no_proxy=api
      - SERVICES=DOCKER
    env_file:
      - .env
      - .secrets
    depends_on:
      - api
