
version: '3.8'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.app
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    env_file:
      - .env
      - .secrets

  dash:
    build:
      context: .
      dockerfile: Dockerfile.dash  
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    command: python index.py
    volumes:
      - ./src/dash:/usr/src/app
    ports:
      - 8005:8050
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    env_file:
      - .env
      - .secrets