
version: '3.8'

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.app
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foo
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    env_file:
      - .env
      - .secrets
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo