
version: '3.8'

services:

  # API docker image / reads and wrangles data
  # returns data via fastapi to dash app
  api:
    build:
      context: ./src
      dockerfile: Dockerfile.api
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    # NOTE: the --reload flag means that edits are automtically redeployed
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8094 --app-dir hyui/src
    volumes:
      - ./:/home/hyui/hyui
    ports:
      - "8094:8094"
    expose:
      - "8000"
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY=apps
      - no_proxy=apps
      - DOCKER=True
    env_file:
      - .env
      - .secrets

  # Dash (Plotly) docker image / web app that visualises results
  # reads data via requests from api app
  apps:
    build:
      context: ./src
      dockerfile: Dockerfile.apps
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    command: gunicorn --chdir hyui/src --bind 0.0.0.0:8095 -w 4 -k gevent --worker-tmp-dir /dev/shm apps.app:server
    volumes:
      - ./:/home/hyui/hyui
    ports:
      - "8095:8095"
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY=api
      - no_proxy=api
      - DOCKER=True
    env_file:
      - .env
      - .secrets
    depends_on:
      - api

  playwright:
    build:
      context: ./src
      dockerfile: Dockerfile.playwright
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    command: pytest hyui/src/tests/e2e --noconftest -m smoke
    volumes:
      - ./:/hyui
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY=api
      - no_proxy=api
      - NO_PROXY=app
      - no_proxy=app
      - DOCKER=True
    env_file:
      - .env
      - .secrets
    depends_on:
      - api
      - apps
