
version: '3.8'

services:
 
  # API docker image / reads and wrangles data
  # returns data via fastapi to dash app
  api:
    build: 
      context: ./src
      dockerfile: Dockerfile.api
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    # NOTE: the --reload flag means that edits are automtically redeployed
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/api:/usr/src/app
    ports:
      - 8094:8000
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - PORT=8000
    env_file:
      - .env
      - .secrets

  # Dash (Plotly) docker image / web app that visualises results
  # reads data via requests from api app
  dash:
    build:
      context: ./src
      dockerfile: Dockerfile.dash  
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    # TODO: this entry point command will run the app in debug mode
    #       should convert to uvicorn or similar server
    command: python index.py
    volumes:
      - ./src/dash:/usr/src/app
    ports:
      - 8095:8050
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    env_file:
      - .env
      - .secrets
    depends_on:
      - api