version: '3'

services:

    dash:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - http_proxy
                - https_proxy
                - HTTP_PROXY
                - HTTPS_PROXY
        container_name: dash_dash
        environment:
            - http_proxy
            - https_proxy
            - HTTP_PROXY
            - HTTPS_PROXY
        volumes:
            - ./data:/data
        ports:
            - "8051:8050"
        command: python src/app.py
