"""
module level config
"""

DEPARTMENTS = (
    "UCH T01 ACUTE MEDICAL",  # 86
    "UCH T01 ENHANCED CARE",  # 20
    "UCH T03 INTENSIVE CARE",  # 37
    "UCH T06 HEAD (T06H)",  # 27
    "UCH T06 CENTRAL (T06C)",  # 25
    "UCH T06 SOUTH PACU",  # 22
    "UCH T06 GYNAE (T06G)",  # 18
    "UCH T07 NORTH (T07N)",  # 45
    "UCH T07 CV SURGE",  # 37
    "UCH T07 SOUTH",  # 33
    "UCH T07 SOUTH (T07S)",  # 23
    "UCH T07 HDRU",  # 20
    "UCH T08 NORTH (T08N)",  # 28
    "UCH T08 SOUTH (T08S)",  # 25
    "UCH T08S ARCU",  # 6
    "UCH T09 SOUTH (T09S)",  # 34
    "UCH T09 NORTH (T09N)",  # 32
    "UCH T09 CENTRAL (T09C)",  # 25
    "UCH T10 SOUTH (T10S)",  # 34
    "UCH T10 NORTH (T10N)",  # 32
    "UCH T10 MED (T10M)",  # 16
    "UCH T11 SOUTH (T11S)",  # 27
    "UCH T11 NORTH (T11N)",  # 25
    "UCH T11 EAST (T11E)",  # 16
    "UCH T11 NORTH (T11NO)",  # 8
    "UCH T12 SOUTH (T12S)",  # 32
    "UCH T12 NORTH (T12N)",  # 23
    "UCH T13 SOUTH (T13S)",  # 31
    "UCH T13 NORTH ONCOLOGY",  # 26
    "UCH T13 NORTH (T13N)",  # 26
    "UCH T14 NORTH TRAUMA",  # 28
    "UCH T14 NORTH (T14N)",  # 28
    "UCH T14 SOUTH ASU",  # 22
    "UCH T14 SOUTH (T14S)",  # 17
    "UCH T15 SOUTH DECANT",  # 21
    "UCH T15 SOUTH (T15S)",  # 21
    "UCH T15 NORTH (T15N)",  # 16
    "UCH T15 NORTH DECANT",  # 15
    "UCH T15 SOUTH DECANT",  # 15
    "UCH T16 NORTH (T16N)",  # 19
    "UCH T16 SOUTH (T16S)",  # 18
    "UCH T16 SOUTH WINTER",  # 17
    "GWB L01 ELECTIVE SURG",  # 37
    "GWB L01 CRITICAL CARE",  # 12
    "GWB L02 NORTH (L02N)",  # 19
    "GWB L02 EAST (L02E)",  # 19
    "GWB L03 NORTH (L03N)",  # 19
    "GWB L03 EAST (L03E)",  # 19
    "GWB L04 NORTH (L04N)",  # 20
    "GWB L04 EAST (L04E)",  # 17
    "WMS W04 WARD",  # 28
    "WMS W03 WARD",  # 27
    "WMS W02 SHORT STAY",  # 20
    "WMS W01 CRITICAL CARE",  # 11
    "NHNN C0 NCCU",
    "NHNN C1 NCCU",
    # "NHNN C1 SURGICAL ITU",
    "NHNN C2 VICTOR HORSLEY",
    "NHNN C3 BERNARD SUNLEY",
    "NHNN C3 DAVID FERRIER",
    "NHNN C4 BLOOMSBURY WRD",
    "NHNN C4 MOLLY LANE FOX",
    "NHNN Q1 LADY ANNE",
    "NHNN Q3 REHABILITATION",
    "NHNN Q4 JOHN YOUNG WRD",
    "NHNN Q5 H JACKSON WARD",
    "NHNN Q6 MAIDA VALE WRD",
    "NHNN Q7 TELEMETRY UNIT",
)

VIRTUAL_ROOMS = (
    "WAITING",
    "CHAIRS",
    "POOL ROOM",
    "DENTAL CHAIRS",
    "ADULT TRIAGE",
    "LOUNGE",
    "ARRIVED",
    "DISCHARGE",
    "WAIT",
    "VIRTUAL GI",
    "VIRTUAL T&O",
    "POOL",
    "CLINIC",
    "OTF",
    "L&D PACU",
    "MAJAX P03 RECOVERY",
    "VIRTUAL UROLOGY",
    "REVIEW AND BLOOD TEST BAY",
    "PHYSIO",
    "PROC",
    "IR",
    "LITHOTRIPSY ROOM",
    "IN TREATMENT",
    "CORRIDOR",
    "LEAVE OF ABSCENCE",
    "KITCHEN",
    "HOME",
    "WAITING ROOM",
    "VIRTUAL ENDOSCOPY",
    "DAYCASE",
    "MAJAX P01 SURGICAL RECEPTION",
    "MAJAX P02 ENDOSCOPY",
)

VIRTUAL_BEDS = (
    "POOL",
    "NONE",
    "ENDO",
    "IMG",
    "OUT PG",
    "IR",
    "WAIT",
    "IR",
    "THR",
    "WAITING",
    "OTF",
    "ARRIVED",
    "CHAIR",
    "VIRTUAL",
    "-",
    "PLASTER ROOM",
    "TREATMENT ROOM",
    "OPHTHALMOLOGY ROOM",
)
