#!/bin/bash

set -o errexit
set -o nounset

# simple declaration
# celery -A main.celery_app worker --loglevel=info

# using watchfiles and passing the above as a string
watchfiles --filter python \
  'celery -A web.app.celery worker --loglevel=info'
