#!/bin/bash

set -o errexit
set -o nounset

rm -f './celerybeat.pid'

# simple declaration
# celery -A web.app.celery beat -l info

# using watchfiles and passing the above as a string
watchfiles --filter python \
  'celery -A web.tasks.celery_app beat --loglevel=info'
