[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hyui-web"
version = "0.0.1"
dependencies = [
    "hyui-models",
    "pandas == 1.5.1",
    "pydantic == 1.10.2",
    "requests == 2.28.1",
    "jupyterlab == 3.5.2",
    "ipython == 8.8.0",
]
