BPID = "ABACUS_"
PAGE_REFRESH_INTERVAL = 10 * 60 * 1000  # 10 mins in milliseconds

SITREP_DEPT2WARD_MAPPING = {
    "UCH T03 INTENSIVE CARE": "T03",
    "UCH T06 SOUTH PACU": "T06",
    "GWB L01 CRITICAL CARE": "GWB",
    "WMS W01 CRITICAL CARE": "WMS",
    "NHNN C0 NCCU": "NCCU0",
    "NHNN C1 NCCU": "NCCU1",
}

WARDS_WITH_MAPS = {
    "UCH T03 INTENSIVE CARE",
    "GWB L01 CRITICAL CARE",
    "WMS W01 CRITICAL CARE",
    "UCH T06 SOUTH PACU",
    "NHNN C0 NCCU",
    "NHNN C1 NCCU",
}
