project:
  type: website
  preview:
    port: 8304

execute:
  freeze: auto

website:
  title: "HYLODE"
  description: Hyperlocal Demand Forecasts for better bed management in the NHS
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: http://172.16.149.202:6001
        text: Application
      - href: user/user.qmd
        text: Documentation
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/HYLODE/HyUI
        aria-label: GitHub
  page-navigation: true  # navigate from one page to the next
  page-footer: |
    Built for the NHS | Developed at UCLH | Supported by NHS-X and NIHR | 2021-2023
  sidebar:
    style: "docked"
    contents:
      - section: "User"
        contents:
          - user/user.qmd
      - section: "Developer"
        contents:
          - developer/setup.qmd
          - developer/demo.qmd
          - developer/deployment.qmd
          - developer/documentation.qmd
          - developer/ide_setup.qmd
          - developer/infrastructure.qmd
      - section: "Vignettes"
        contents:
          - vignettes/vignettes.qmd
      # - section: "Contributing"
      #   contents:
      #     - contributor_guide/CODE_OF_CONDUCT.qmd
      #     - contributor_guide/CONTRIBUTING.qmd
      #     - contributor_guide/pre_commit_hooks.qmd
      #     - contributor_guide/updating_gitignore.qmd
  repo-url: https://github.com/hylode/hyui
  repo-actions: [edit, issue]
  repo-subdir: hyui

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script defer data-domain="uclhal.org" src="https://plausible.io/js/script.js"></script>
    link-external-icon: true
    link-external-newwindow: true
