SITREP_DEPT2WARD_MAPPING: dict = {
    "UCH T03 INTENSIVE CARE": "T03",
    "UCH T06 SOUTH PACU": "T06",
    "GWB L01 CRITICAL CARE": "GWB",
    "WMS W01 CRITICAL CARE": "WMS",
    "NHNN C0 NCCU": "NHNNC0",
    "NHNN C1 NCCU": "NHNNC1",
}
