name: Unit Test Packages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "code/utils[test]"
          pip install -e "code/models[test]"
          pip install -e "code/web[test]"
          pip install -e "code/api[test]"
      - name: Test with pytest
        working-directory: ./code
        # Ideally we should not need all the environment variables to test.
        run: |
          env $(grep -v '^#' .env.example | xargs) pytest
