name: Unit Test Packages

on: [push]

jobs:
  continuous-integration:
    env:
      API_STAR_DSN: "postgresql+psycopg2://username:password@host:1234/uds"
      API_CABOODLE_DSN: "mssql+pyodbc://username:password@host:1234/caboodle_report"
      API_CLARITY_DSN: "mssql+pyodbc://username:password@host:1234/clarity_report"
      API_BASEROW_EMAIL: foo@bar.com
      API_BASEROW_PASSWORD: foobar
      API_BASEROW_USERNAME: foobar
      API_BASEROW_APPLICATION_NAME: hyui
      API_BASEROW_URL: http://foo.bar
      API_HYCASTLE_URL: http://foo.bar
      API_HYMIND_URL: http://foo.bar
      API_TOWERMAIL_URL: http://foo.bar

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "models[test]"
          pip install -e "web[test]"
          pip install -e "api[test]"
      - name: Test with pytest
        working-directory: ./
        # Ideally we should not need all the environment variables to test.
        run: pytest
