# basic github workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER: True
  ENV: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the lint_etc job
  lint_etc:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      # Lint the files
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test_unit:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3
      # make a dummy .env file else this will fail
      - name: unit tests within docker
        run: |
          mv .env.github_actions .env
          set -o allexport; source .env; set +o allexport
          export HYUI_UID=9998
          docker compose up -d --build
          docker compose exec api pytest tests/unit
          docker compose exec apps pytest tests/unit

  test_e2e:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set-up docker network
        run: |
          mv .env.github_actions .env
          set -o allexport; source .env; set +o allexport
          export HYUI_UID=9998
          docker compose up -d --build
          docker compose run playwright
