name: Unit Test Packages

on: [push]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "models[test]"
          pip install -e "web[test]"
          pip install -e "api[test]"
      - name: Test with pytest
        working-directory: ./
        # Ideally we should not need all the environment variables to test.
        run: pytest
